Vagrant.configure("2") do |config|

    config.vm.define "web" do |web|    
        web.vm.box = "bento/ubuntu-24.04"
        web.vm.box_version = "202502.21.0"
        web.vm.network "private_network", ip: "192.168.56.2"
        # config.vm.network "public_network"
        web.vm.synced_folder "../wordpress", "/vagrant"
        web.vm.provider "virtualbox" do |vb|
            vb.cpus = 3
            vb.memory = "2048"
        end
        web.vm.provision "shell", inline: <<-SHELL
          sudo apt update
          sudo apt install apache2 \
                    ghostscript \
                    libapache2-mod-php \
                    php \
                    php-bcmath \
                    php-curl \
                    php-imagick \
                    php-intl \
                    php-json \
                    php-mbstring \
                    php-mysql \
                    php-xml \
                    php-zip -y
          sudo mkdir -p /srv/www
          sudo chown www-data: /srv/www
          curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
          cp /vagrant/wordpress.conf /etc/apache2/sites-available/wordpress.conf
          sudo a2ensite wordpress
          sudo a2enmod rewrite
          sudo a2dissite 000-default
          sudo service apache2 reload
        SHELL
    end
 
    config.vm.define "database" do |db|
      db.vm.box = "bento/ubuntu-24.04"
      db.vm.box_version = "202502.21.0"
      db.vm.network "private_network", ip: "192.168.56.3"
      db.vm.provider "virtualbox" do |vb|
            vb.cpus = 3
            vb.memory = "2048"
      end
      db.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y mysql-server
        mysql -u root -e 'CREATE DATABASE wordpress;'
        mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "admin123";'
        mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
        mysql -u root -e 'FLUSH PRIVILEGES;'
        sudo service mysql start
        sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
        sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
        sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
        sudo -u www-data sed -i 's/password_here/admin123/' /srv/www/wordpress/wp-config.php
      SHELL
    end
end
