# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"
  config.vm.network "private_network", ip: "192.168.56.6"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install fontconfig openjdk-21-jre -y
        sudo wget -O /etc/apt/keyrings/jenkins-keyring.asc \
        https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc]" \
        https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null
        apt-get update
        apt-get install jenkins -y
        echo "Jenkins installed Successfully."

  SHELL

end
